# Generated by Django 2.2.1 on 2020-02-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='cfg_cmd_sim',
            field=models.FloatField(null=True, verbose_name='cfg_cmd_sim'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cfg_esclavo',
            field=models.IntegerField(null=True, verbose_name='cfg_esclavo'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cfg_hab_alarma_h',
            field=models.IntegerField(null=True, verbose_name='cfg_hab_alarma_h'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cfg_hab_alarma_hh',
            field=models.IntegerField(null=True, verbose_name='cfg_hab_alarma_hh'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cfg_hab_alarma_l',
            field=models.IntegerField(null=True, verbose_name='cfg_hab_alarma_l'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cfg_hab_alarma_ll',
            field=models.IntegerField(null=True, verbose_name='cfg_hab_alarma_ll'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cfg_hab_sim',
            field=models.IntegerField(null=True, verbose_name='cfg_hab_sim'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cfg_hab_var',
            field=models.IntegerField(null=True, verbose_name='cfg_hab_var'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cfg_max_eu',
            field=models.FloatField(null=True, verbose_name='cfg_max_eu'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cfg_max_raw',
            field=models.FloatField(max_length=10, null=True, verbose_name='cfg_max_raw'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cfg_min_eu',
            field=models.FloatField(max_length=10, null=True, verbose_name='cfg_min_eu'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cfg_min_raw',
            field=models.FloatField(max_length=10, null=True, verbose_name='cfg_min_raw'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cfg_mth_puerto',
            field=models.IntegerField(null=True, verbose_name='cfg_mth_puerto'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cfg_reg',
            field=models.IntegerField(null=True, verbose_name='cfg_reg'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cfg_rtu_baud',
            field=models.IntegerField(null=True, verbose_name='cfg_rtu_baud'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cfg_rtu_puerto',
            field=models.IntegerField(null=True, verbose_name='cfg_rtu_puerto'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cfg_sp_alarma_h',
            field=models.IntegerField(null=True, verbose_name='cfg_sp_alarma_h'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cfg_sp_alarma_hh',
            field=models.IntegerField(null=True, verbose_name='cfg_sp_alarma_hh'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cfg_sp_alarma_l',
            field=models.FloatField(null=True, verbose_name='cfg_sp_alarma_l'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cfg_sp_alarma_ll',
            field=models.FloatField(null=True, verbose_name='cfg_sp_alarma_ll'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='sts_alarma_h',
            field=models.IntegerField(null=True, verbose_name='sts_alarma_h'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='sts_alarma_hh',
            field=models.IntegerField(null=True, verbose_name='sts_alarma_hh'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='sts_alarma_l',
            field=models.IntegerField(null=True, verbose_name='sts_alarma_l'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='sts_alarma_ll',
            field=models.IntegerField(null=True, verbose_name='sts_alarma_ll'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='sts_data_eu',
            field=models.FloatField(null=True, verbose_name='sts_data_eu'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='sts_data_raw',
            field=models.FloatField(null=True, verbose_name='sts_data_raw'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='sts_falla_io',
            field=models.FloatField(null=True, verbose_name='sts_falla_io'),
        ),
    ]
