# Generated by Django 2.2.1 on 2020-02-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_auto_20200227_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='cfg_hab_alarma_l',
            field=models.FloatField(null=True, verbose_name='cfg_hab_alarma_l'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cfg_hab_alarma_ll',
            field=models.FloatField(null=True, verbose_name='cfg_hab_alarma_ll'),
        ),
    ]
