# Generated by Django 2.2.1 on 2020-03-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0005_nombres'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nombres',
            table='nombre_variable',
        ),
    ]
