# Generated by Django 2.2.1 on 2020-03-04 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0006_auto_20200301_1101'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='datos_variable',
            table='datos_variable',
        ),
    ]
