# Generated by Django 2.2.1 on 2020-03-08 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0007_auto_20200303_1944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nombres',
        ),
        migrations.AlterModelTable(
            name='datos_variable',
            table='datos_tag',
        ),
    ]
