# Generated by Django 2.2.1 on 2020-03-08 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0008_auto_20200308_1410'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datos_Variable',
            new_name='Datos_Tag',
        ),
        migrations.AlterModelOptions(
            name='datos_tag',
            options={'ordering': ['id_dt'], 'verbose_name': 'Datos_Variable', 'verbose_name_plural': 'Datos_Variables'},
        ),
        migrations.RenameField(
            model_name='datos_tag',
            old_name='id',
            new_name='id_dt',
        ),
    ]
