# Generated by Django 2.2.1 on 2020-03-08 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0009_auto_20200308_1436'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
    ]
